<?php

namespace WpConnectionBundle\Repository;

/**
 * WpPostmetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WpPostmetaRepository extends \Doctrine\ORM\EntityRepository {

    public function findByNameAttachedFile($name) {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $properNameArray = explode('/', $name);
        $properName = array_pop($properNameArray);
        $qb->select('p')
                ->from('WpConnectionBundle:WpPostmeta', 'p')
                ->where('p.metaKey  = :metaKey')
                ->andWhere('p.metaValue LIKE :name')
                ->setParameters(['name' => '%'.$properName, 'metaKey' => '_wp_attached_file']);

        return $qb->getQuery()->getOneOrNullResult();
    }

}
