<?php

namespace WpConnectionBundle\Repository;

/**
 * WpPostsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WpPostsRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findByProduct()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('p')
                ->from('WpConnectionBundle:WpPosts', 'p', 'p.id')
                ->where('p.postType  = :product')
                ->setParameter('product', 'Product');

        return $qb->getQuery()->getResult();
    }
    
    public function getPostsByName()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('p')
                ->from('WpConnectionBundle:WpPosts', 'p', 'p.postTitle')
                ->where('p.postType  = :product')
                ->setParameter('product', 'Product');

        return $qb->getQuery()->getResult();
    }
}
